const Images = {
    acm: require('../../img/acm.jpg'),
    amourady: require('../../img/armen.jpg'),
    aphilipe: require('../../img/arne.jpg'),
    bwakasa: require('../../img/blake.jpg'),
    btjanaka: require('../../img/bryon.jpg'),
    craut: require('../../img/chinmay.jpg'),
    cdipalma: require('../../img/chris.jpg'),
    zhonghas: require('../../img/frank.jpg'),
    renjied: require('../../img/jacky.jpg'),
    jtuyls: require('../../img/jens.jpg'),
    junliw1: require('../../img/junlin.jpg'),
    kgajulap: require('../../img/karthik.jpg'),
    mnovitia: require('../../img/meta.jpg'),
    pooyak: require('../../img/pooya.jpg'),
    timothy4: require('../../img/tim.jpg'),
    tujohnso: require('../../img/timj.jpg'),
    pashak: require('../../img/pasha.jpg'),
    wangka1: require('../../img/kevin.jpg'),
    chult: require('../../img/linh.jpg'),
    ofri: require('../../img/ofri.jpg'),
    arvind: require('../../img/arvind.jpg'),
    allen: require('../../img/allen.jpg'),
    shaun: require('../../img/shaun.jpg'),
    pattis: require('../../img/pattis.jpg'),
    kirkmc: require('../../img/kirkmc.jpg'),
    bmchu1: require('../../img/bmchu1.jpg'),
    sdowdle: require('../../img/sdowdle.jpg'),
    pbaldara: require('../../img/pbaldaray.jpg'),
    // jsley: require('../../img/jley.jpg'),
    jsley: require('../../img/jley2.png'),
    mantoun: require('../../img/mantian.gif'),
    rhsakuma: require('../../img/rhsakuma.jpg'),
    tejasv: require('../../img/tejasv.jpg'),
    ryansy: require('../../img/ryansy.jpg')
};

export default Images;
